import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(SCRIPT_DIR, '..');

export function displayVersion(version) {
  return String(version).replace(/\.0$/, '');
}

export function buildVersionInfo(pkg) {
  const version = String(pkg.version || '').trim();
  if (!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version)) {
    throw new Error(`package.json version must use npm semver, got "${version}"`);
  }
  const display = displayVersion(version);
  return {
    name: 'Family Cashflow',
    version,
    displayVersion: display,
    label: `Family Cashflow ${display}`,
    archiveName: `family_cashflow_v${version}.tar.gz`,
  };
}

export function renderVersionFile(info) {
  return `// Generated by npm run build from package.json. Do not edit manually.
window.FAMILY_CASHFLOW_VERSION = Object.freeze({
  name: ${JSON.stringify(info.name)},
  version: ${JSON.stringify(info.version)},
  displayVersion: ${JSON.stringify(info.displayVersion)},
  label: ${JSON.stringify(info.label)},
  archiveName: ${JSON.stringify(info.archiveName)},
});
`;
}

export function writeVersionFile(root = ROOT) {
  const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
  const info = buildVersionInfo(pkg);
  const target = path.join(root, 'public', 'js', 'app-version.js');
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, renderVersionFile(info));
  console.log(`Building ${info.label} (package ${info.version})`);
  return info;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--archive-name')) {
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
    process.stdout.write(buildVersionInfo(pkg).archiveName);
  } else {
    writeVersionFile();
  }
}
